# Generated by Django 3.2.18 on 2024-10-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(max_length=50)),
                ('color_option', models.CharField(max_length=50)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoesize', to='store.product')),
            ],
        ),
    ]
